/* DESCRIBE LAS ACCIONES QUE SE HACEN EN LA APP */
export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';
export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO';
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR';
// DESCARGA DE PRODUCTOS
export const DESCARGAR_PRODUCTOS = 'DESCARGAR_PRODUCTOS'
export const DESCARGAR_PRODUCTOS_EXITO = 'DESCARGAR_PRODUCTOS_EXITO'
export const DESCARGAR_PRODUCTOS_ERROR = 'DESCARGAR_PRODUCTOS_ERROR'